#include "images.h"

const ext_img_desc_t images[40] = {
    { "frame_1", &img_frame_1 },
    { "frame_2", &img_frame_2 },
    { "frame_3", &img_frame_3 },
    { "frame_4", &img_frame_4 },
    { "frame_5", &img_frame_5 },
    { "frame_6", &img_frame_6 },
    { "frame_7", &img_frame_7 },
    { "frame_8", &img_frame_8 },
    { "frame_9", &img_frame_9 },
    { "frame_10", &img_frame_10 },
    { "frame_11", &img_frame_11 },
    { "frame_12", &img_frame_12 },
    { "frame_13", &img_frame_13 },
    { "frame_14", &img_frame_14 },
    { "frame_15", &img_frame_15 },
    { "frame_16", &img_frame_16 },
    { "frame_17", &img_frame_17 },
    { "frame_18", &img_frame_18 },
    { "frame_19", &img_frame_19 },
    { "frame_20", &img_frame_20 },
    { "frame_21", &img_frame_21 },
    { "frame_22", &img_frame_22 },
    { "frame_23", &img_frame_23 },
    { "frame_24", &img_frame_24 },
    { "frame_25", &img_frame_25 },
    { "frame_26", &img_frame_26 },
    { "frame_27", &img_frame_27 },
    { "frame_28", &img_frame_28 },
    { "frame_29", &img_frame_29 },
    { "frame_30", &img_frame_30 },
    { "frame_31", &img_frame_31 },
    { "frame_32", &img_frame_32 },
    { "frame_33", &img_frame_33 },
    { "frame_34", &img_frame_34 },
    { "frame_35", &img_frame_35 },
    { "frame_36", &img_frame_36 },
    { "frame_37", &img_frame_37 },
    { "frame_38", &img_frame_38 },
    { "frame_39", &img_frame_39 },
    { "frame_40", &img_frame_40 },
};